name: Linter Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.3'
      - name: Install
        env:
          TOKEN: ${{ secrets.MY-TOKEN }}
        run: make install
      - name: Launch linter
        run: make lint
